config/routes.rb
Rails.application.routes.draw do   
  get 'hello_world', to: 'hello_world#index'
  root 'welcome#index'

  get 'votes/recently_added' => 'votes#recently_added', as: :recently_added_votes
  get 'votes/add_parent' => 'votes#add_parent', as: :add_parent_vote
  post 'votes/email_invite' => 'votes#email_invite', as: :email_invite_votes

  get 'admin/:admin_hash' => 'welcome#admin', as: :admin_index
  post 'admin/:admin_hash' => 'welcome#admin_upload', as: :admin_upload

  scope "(:locale)" do
    get '' => 'welcome#index', as: :locale_root
    get 'appeal' => 'welcome#appeal', as: :appeal
    resources :votes, :only => [:new, :index, :create]
    resources :comments, :only => [:new, :index, :create]
    get 'votes/:secret_token' => 'votes#show', as: :vote
    get 'download' => 'welcome#download', as: :download
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  #include Humanizer
  attr_accessor :bypass_humanizer
  #require_human_on :create, :unless => :bypass_humanizer

  #validates :name, presence: true
  validates :language, presence: true
  #validates :email, confirmation: true
  #validates :email, presence: true, uniqueness: true, email: true
  #validates :email_confirmation, presence: true
  validates :ip, presence: true
  validates_format_of :ip, :with => /\A(\d{1,3}\.){3}\d{1,3}\z/
  validates :vote, presence: true
  validate :validate_language_literal
  validate :validate_theme

  after_initialize :downcase_theme

  belongs_to :vote

  def downcase_theme
    self.theme.downcase! unless theme.blank?
  end

  def validate_theme
    themes = %w(administration water climate plastic-waste protected-areas)
    if themes.index(theme).nil?
      errors.add(:theme, "is not valid")
    end
  end

  def validate_language_literal
    if Language.names.index(language).nil?
      errors.add(:language, "is not valid")
    end
  end

  def email_comment
    VoteMailer.new_comment(self).deliver_now
  end

  def self.translated_themes
    {
      "administration" => _("Administration"),
      "water" => _("Water"),
      "climate" => _("Climate"),
      "plastic-waste" => _("Plastic Waste"),
      "protected-areas" => _("Protected Areas")
    }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit]

  # GET /comments
  # GET /comments.json
  # def index
  #  @comments = Comment.all
  #  render layout: "simple_layout"
  # end

  # GET /comments/1
  # GET /comments/1.json
  # def show
  # end

  # GET /comments/new
  def new
    unless session[:current_vote_id]
      redirect_to new_vote_path(locale: locale)
      return
    end

    vote = Vote.where(id: session[:current_vote_id]).first
    unless vote
      redirect_to new_vote_path(locale: locale)
      return
    end

    @vote = vote
    @comment = Comment.new
  end

  # GET /comments/1/edit
  # def edit
  # end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.ip = request.env["REMOTE_ADDR"]
    @comment.bypass_humanizer = true if Rails.env.test?

    unless session[:current_vote_id]
      redirect_to new_vote_path(locale: locale)
      return
    end

    unless RecaptchaVerifier.verify(params["g-recaptcha-response"])
      redirect_to new_vote_path(locale: locale)
      return
    end

    vote = Vote.where(id: session[:current_vote_id]).first
    unless vote
      redirect_to new_vote_path(locale: locale)
      return
    end

    @vote = vote
    @comment.vote = vote

    respond_to do |format|
      if @comment.save
        @comment.email_comment
        msg = _("Comment was successfully created.")
        values = {
          locale: locale,
          secret_token: vote.secret_token
        }
        format.html { redirect_to vote_path(values), notice: msg }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  # def update
  #   respond_to do |format|
  #     if @comment.update(comment_params)
  #       format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @comment }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @comment.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /comments/1
  # DELETE /comments/1.json
  # def destroy
  #   @comment.destroy
  #   respond_to do |format|
  #     format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:topic, :body, :email, :email_confirmation, :theme, :language, :name, :humanizer_answer, :humanizer_question_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<script>
  $(document).ready(function() {
    function showTopic(el) {
      $(".comment-topic").each(function(ind,el) {
        $(el).css("display","none")
      })
      $(".comment-area").show();
      $(".comment-"+el.value).show();
    }
    window.showTopic = showTopic
  });
</script>

<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:
      </h2>
      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label _("Choose the language") %><br>
    <%# f.text_field :language %>
    <%= f.select(:language, Language.translated_select_options) %>
  </div>

  <div class="field">
    <%= f.label _("Choose the topic") %><br/>
    <% topics = %w(administration water climate plastic-waste protected-areas) 
       descriptions = {
         "administration" => _("The activities of the United Armies must be controlled by a common, international organ."),
         "water" => _("The United Armies must ensure sufficient water availability everywhere for the needs of people and life."),
         "climate" => _("The resources and capacity of the United Armies must be directed to reforestation of the deserts."),
         "plastic-waste" => _("The United Armies must collect the plastic waste from the oceans and shores."),
         "protected-areas" => _("The United Armies must protect the areas reserved for nature.")
       }
       topics.each do |topic|
    %>
       <p>
       <label for="<%= topic %>">
         <%= radio_button("comment","theme", topic, onChange: "showTopic(this)", :id => topic) %> 
         <%= Comment.translated_themes[topic] %>
       </label>
       </p>
    <% end %>
  </div>

  <div class="comment-area">
    <% topics.each do |topic| %>
      <div class="comment-topic comment-<%= topic %>">
        <h1 class="page-header"><%= Comment.translated_themes[topic] %></h1>
        <%= image_tag("#{topic}.jpg", :class => "img-responsive img-rounded") %>
        <p class="lead">
          <%= _(descriptions[topic]) %>
        </p>
      </div>
    <% end %>

    <br style="clear:both"/>

    <div class="field">
      <%= @vote.name %> (<%= @vote.email %>)
    </div>
    <div class="field">
      <%= f.label _('Comment (max 1000 characters)') %><br>
      <%= f.text_area :body, :class => "form-control" %>
    </div>
    <div class="field">
      <div class="g-recaptcha" data-sitekey="6LfwgBQTAAAAAJrdJfpdvnMhibW4iUFJRdlK0ZXb"></div>
    </div>
    <div class="field">
      <%# f.label :humanizer_answer, @comment.humanizer_question %>
      <%# f.text_field :humanizer_answer, :class => "form-control" %>
      <%# f.hidden_field :humanizer_question_id %>
    </div>
    <div class="actions">
      <%= f.submit _("Add"), :class => "btn btn-primary form-control" %>
    </div>
  </div>
  
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1><%= _("Listing comments") %></h1>

<table class="table table-responsive">
  <thead>
    <tr>
      <th><%= _("Topic") %></th>
      <th><%= _("Comment") %></th>
      <th><%= _("Email") %></th>
      <th><%= _("Language") %></th>
      <th><%= _("Name") %></th>
      <th><%= _("IP") %></th>
      <th><%= _("Created at") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.theme %></td>
        <td><%= comment.body %></td>
        <td><%= comment.email %></td>
        <td><%= comment.language %></td>
        <td><%= comment.name %></td>
        <td><%= comment.ip %></td>
        <td><%= comment.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<!-- Content -->
<div class="content clearfix">

  <!-- Fullscreen Slider Section -->
  <section class="section-block featured-media tm-slider-parallax-container">
    <div class="tm-slider-container full-width-slider" data-featured-slider data-progress-bar="false" data-parallax data-parallax-fade-out data-auto-advance data-animation="slide" data-scale-under="960">
      <ul class="tms-slides">
	<li class="tms-slide" data-image data-force-fit data-overlay-bkg-color="#000000" data-overlay-bkg-opacity="0.3">
	  <div class="tms-content">
	    <div class="tms-content-inner center left-on-mobile v-align-middle">
	      <div class="row">
		<div class="column width-12">
		  <h1 class="tms-caption title-xlarge color-white lspacing-medium no-margin-bottom weight-bold" data-animate-in="opacity:0;scale:1.5px;duration:600ms;easing:easeFastSlow;" data-no-scale>
                    <%= _("Comments") %>
                  </h1>
		  <div class="clear"></div>
		  <h5 class="tms-caption color-white lspacing-medium mt-20" data-animate-in="opacity:0;transY:50px;duration:600ms;delay:300ms;easing:easeFastSlow;" data-no-scale>
                    <%= _("Make an initiative for the action of the United Armies.") %>
                  </h5>
		</div>
	      </div>
	    </div>
	  </div>
	  <img data-src="/images/slide-2-fs.jpg" data-retina src="/images/blank.png" alt=""/>
	</li>
      </ul>
    </div>
  </section>
  <!-- Fullscreen Slider Section End -->

  <!-- Feature Column Section -->
  <div id="featured-trips" class="section-block replicable-content">
    <div class="row">

      <h1 class="page-header"></h1>
      <p class="lead">
        <%= _("Rules for Comments") %>        
      </p>
      <p>
        <%= _("Suggest a new task for the Action of the United Armies not presented here.") %></br>
        <%= _("Positive initiations will be published.") %></br>
        <%= _("The Suggested task must benefit the whole world.") %></br>
        <%= _("Present the task with max. 1000 characters.") %></br>
        <%= _("Make the initiative using some of the UN:s official languages (6).") %></br>
        <%= _("Would you like to have the initiative in your language – please, contact us!") %><br/>
      </p>
      
      <%= render 'form' %>
      
      <div style="height:200px"></div>
      
    </div>
  </div>
</div>

app/views/comments/show.html.erb
<p>
  <strong>Topic:</strong>
  <%= @comment.topic %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Email:</strong>
  <%= @comment.email %>
</p>

<p>
  <strong>Language:</strong>
  <%= @comment.language %>
</p>

<p>
  <strong>Name:</strong>
  <%= @comment.name %>
</p>