config/routes.rb
Rails.application.routes.draw do   
  get 'hello_world', to: 'hello_world#index'
  root 'welcome#index'

  get 'votes/recently_added' => 'votes#recently_added', as: :recently_added_votes
  get 'votes/add_parent' => 'votes#add_parent', as: :add_parent_vote
  post 'votes/email_invite' => 'votes#email_invite', as: :email_invite_votes

  get 'admin/:admin_hash' => 'welcome#admin', as: :admin_index
  post 'admin/:admin_hash' => 'welcome#admin_upload', as: :admin_upload

  scope "(:locale)" do
    get '' => 'welcome#index', as: :locale_root
    get 'appeal' => 'welcome#appeal', as: :appeal
    resources :votes, :only => [:new, :index, :create]
    resources :comments, :only => [:new, :index, :create]
    get 'votes/:secret_token' => 'votes#show', as: :vote
    get 'download' => 'welcome#download', as: :download
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  after_action :add_flash_to_header
  before_action :set_locale

  private

  def add_flash_to_header
    # only run this in case it's an Ajax request.
    return unless request.xhr?
    # add flash to header
    response.headers['X-Flash'] = flash.to_h.to_json
    # make sure flash does not appear on the next page
    flash.discard
  end

  def set_locale
    FastGettext.text_domain = 'unite-the-armies'
    FastGettext.available_locales = Language::LOCALES.values

    # accept only valid locale values
    loc = Language::LOCALES.values.index(params[:locale].try(:to_sym)).nil? ? nil : params[:locale]

    FastGettext.set_locale(
                           loc ||
                           session[:locale] ||
                           request.env['HTTP_ACCEPT_LANGUAGE'] || :en
                           )
    if session[:locale] and (session[:locale].to_sym != I18n.locale)
      puts "Clearing cache, session:#{session[:locale]} locale:#{I18n.locale}"
      Rails.cache.clear
    end
    session[:locale] = I18n.locale = FastGettext.locale
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  BOOTSTRAP_FLASH_MSG = {
    success: 'alert-success',
    error: 'alert-error',
    alert: 'alert-block',
    notice: 'alert-info'
  }

  def bootstrap_class_for(flash_type)
    BOOTSTRAP_FLASH_MSG.fetch(flash_type, flash_type.to_s)
  end

  def flash_messages
    flash.map do |name, msg|
      flash_classes = ["alert", "alert-dismissable", bootstrap_class_for(name.to_sym)]
      content_tag(:div, class: flash_classes) do
        html = button_tag(type: :button, class: :close, :"data-dismiss" => "alert") do
          "&times;".html_safe
        end
        html << ("<h2>"+msg+"</h2>").html_safe
        html
      end
    end.join.html_safe
  end

end

app/views/application/_flags.html.erb
<li>
  <a class="contains-sub-menu" data-no-turbolink='true' target="_top" href="<%= url_for only_path: false, locale: :ar %>" onclick="window.location = $(this).attr('href')">
    <%= image_tag "blank.gif", class: "flag flag-sa", alt: _("Arabic") %>
  </a>
</li>
<li>
  <a class="contains-sub-menu" data-no-turbolink='true' target="_top" href="<%= url_for only_path: false, locale: :zh %>" onclick="window.location = $(this).attr('href')">
    <%= image_tag "blank.gif", class: "flag flag-cn", alt: _("Chinese") %>
  </a>
</li>
<li>
  <a class="contains-sub-menu" data-no-turbolink='true' target="_top" href="<%= url_for only_path: false, locale: :en %>" onclick="window.location = $(this).attr('href')">
    <%= image_tag "blank.gif", class: "flag flag-gb", alt: _("English") %>
  </a>
</li>
<li>
  <a class="contains-sub-menu" data-no-turbolink='true' target="_top" href="<%= url_for only_path: false, locale: :fr %>" onclick="window.location = $(this).attr('href')">
    <%= image_tag "blank.gif", class: "flag flag-fr", alt: _("French") %>
  </a>
</li>
<li>
  <a class="contains-sub-menu" data-no-turbolink='true' target="_top" href="<%= url_for only_path: false, locale: :ru %>" onclick="window.location = $(this).attr('href')">
    <%= image_tag "blank.gif", class: "flag flag-ru", alt: _("Russian") %>
  </a>
</li>
<li>
  <a class="contains-sub-menu" data-no-turbolink='true' target="_top" href="<%= url_for only_path: false, locale: :es %>" onclick="window.location = $(this).attr('href')">
    <%= image_tag "blank.gif", class: "flag flag-es", alt: _("Spanish") %>
  </a>
</li>
<li>
  <a class="contains-sub-menu" data-no-turbolink='true' target="_top" href="<%= url_for only_path: false, locale: :de %>" onclick="window.location = $(this).attr('href')">
    <%= image_tag "blank.gif", class: "flag flag-de", alt: _("German") %>
  </a>
</li>
<li>
  <a class="contains-sub-menu" data-no-turbolink='true' target="_top" href="<%= url_for only_path: false, locale: :se %>" onclick="window.location = $(this).attr('href')">
    <%= image_tag "blank.gif", class: "flag flag-se", alt: _("Swedish") %>
  </a>
</li>
<li>
  <a class="contains-sub-menu" data-no-turbolink='true' target="_top" href="<%= url_for only_path: false, locale: :fi %>" onclick="window.location = $(this).attr('href')">
    <%= image_tag "blank.gif", class: "flag flag-fi", alt: _("Finnish") %>
  </a>
</li>

app/views/application/_footer.html.erb
<!-- Footer -->
<footer class="footer">
  <div class="footer-top">
    <div class="row">
      <div class="column width-4">
        <div class="widget">
          <%= link_to VESL_URL, target: "_blank" do %>
              <h4 class="widget-title">
                <%= _(VESL_NAME) %>
              </h4>
              <%= image_tag "veslogo-scaled.jpg", alt: _(VESL_NAME) %>
          <% end %>
        </div>
        <div class="widget">
          <%= link_to TEP_URL, target: "_blank" do %>
              <h4 class="widget-title">
                <%= _(TEP_NAME) %>
              </h4>
              <%= image_tag "teplogo-scaled.jpg", alt: _(TEP_NAME) %>
          <% end %>
        </div>
      </div>
      <div class="column width-4">
        <div class="widget">
          <h4 class="widget-title"><%= _("About Us") %></h4>
          <ul class="list-group small">
            <li>
              <%= link_to _(VESL_NAME), VESL_URL, target: "_blank" %>
            </li>
            <li><span class="post-info"><span class="post-date">
                  Anyara Granskog
                </span></span></li>
            <li><span class="post-info"><span class="post-date">
                  Valtteri Hirvonen (the landscape photos)
                </span></span></li>
            <li><span class="post-info"><span class="post-date">
                  Hayang Hu
                </span></span></li>
            <li><span class="post-info"><span class="post-date">
                  Elli Kempas
                </span></span></li>
            <li><span class="post-info"><span class="post-date">
                  Ulla Klötzer
                </span></span></li>
            <li><span class="post-info"><span class="post-date">
                  Riikka Kämppi
                </span></span></li>
            <li><span class="post-info"><span class="post-date">
                  Lea Launokari
                </span></span></li>
            <li><span class="post-info"><span class="post-date">
                  Pekka Lehtinen
                </span></span></li>
            <li><span class="post-info"><span class="post-date">
                  Ulf Lindström
                </span></span></li>
            <li><span class="post-info"><span class="post-date">
                  Pentti Linkola
                </span></span></li>
            <li><span class="post-info"><span class="post-date">
                  Harriet Lonka
                </span></span></li>
            <li><span class="post-info"><span class="post-date">
                  Tommi Lukkarinen
                </span></span></li>
            <li><span class="post-info"><span class="post-date">
                  Mika Mattila
                </span></span></li>
            <li><span class="post-info"><span class="post-date">
                  Nina Motaleff
                </span></span></li>
            <li><span class="post-info"><span class="post-date">
                  Saku Mättö
                </span></span></li>
            <li><span class="post-info"><span class="post-date">
                  Aurora Paloheimo
                </span></span></li>
            <li><span class="post-info"><span class="post-date">
                  Eero Paloheimo
                </span></span></li>
            <li><span class="post-info"><span class="post-date">
                  Kimmo Pietiläinen
                </span></span></li>
            <li><span class="post-info"><span class="post-date">
                  Sanna Saastamoinen-Barrois
                </span></span></li>
            <li><span class="post-info"><span class="post-date">
                  Emmi Seppänen
                </span></span></li>
            <li><span class="post-info"><span class="post-date">
                  Adrian Soto
                </span></span></li>
            <li><span class="post-info"><span class="post-date">
                  Joni Töyrylä
                </span></span></li>
            <li><span class="post-info"><span class="post-date">
                  Tere Vadén
                </span></span></li>
            <li><span class="post-info"><span class="post-date">
                  Michael Wynne-Ellis
                </span></span></li>
          </ul>
          <p>
            <%= _("Contact our Campaign Assistant") %>:<br>
            <a class="button small" style="color:#333 !important" href="mailto:<%= CAMPAIGN_ASSISTANT_EMAIL %>"><%= CAMPAIGN_ASSISTANT_EMAIL %></a>
          </p>
        </div>
      </div>
      <div class="column width-3" style="padding-left: 0">
        <div class="widget">
          <h4 class="widget-title"><%= _("Recent Votes") %></h4>
          <!--div id="recent_votes"></div-->
          <table id="recent_votes" class="table">
            <thead>
              <tr class="recent_votes_header">
                <th><%= _("Country") %></td>
                <th><%= _("Name") %></td>
              </tr>
            </thead>
            <tbody></tbody>
          </table>

        </div>
      </div>
      <div class="column width-1">
        <ul class="social-list list-horizontal pull-right clear-float-on-mobile">
          <li>
            <%= link_to UNITE_FACEBOOK_URL, target: "_blank" do %>
                <span class="icon-facebook-with-circle medium"></span>
            <% end %>
          </li>
          <li>
            <a href="#">
              <span class="icon-twitter-with-circle medium"></span>
            </a>
          </li>
          <li>
            <%= link_to UNITE_YOUTUBE_URL, target: "_blank" do %>
                <span class="icon-youtube-with-circle  medium"></span>
            <% end %>
          </li>
          <li>
            <%= link_to UNITE_GOOGLEPLUS_URL, target: "_blank" do %>
                <span class="icon-google-with-circle medium"></span>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

<footer class="footer">
  <div class="footer-top">
    <div class="row">
    <!-- <div class="column width-12 center"> -->
      <div class="column width-4 left">
        v.1.1 with Ruby 3.3.6, Rails 8.0, React 18.2
      </div>

      <div class="column width-8 right">
        <%= link_to("Github", GITHUB_URL, target: "_blank") %>
      </div>
    </div>
  </div>
</footer>

app/views/application/_head.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta content="width=device-width,initial-scale=1.0,maximum-scale=1.0" name="viewport">
<meta name="twitter:widgets:theme" content="light">

<meta property="og:type"          content="website" />
<meta property="og:title"         content="<%= UNITE_TITLE %>" />
<meta property="og:description"   content="<%= UNITE_DESCRIPTION %>" />
<meta property="og:url"           content="<%= UNITE_ROOT_URL %>" />
<meta property="og:image"         content="<%= image_url(UNITE_LOGO) %>" />

<link rel="shortcut icon" type="image/x-icon" href="/images/theme-mountain-favicon.ico">

<!-- Font -->
<link href='https://fonts.googleapis.com/css?family=Lato:300,400,700%7CRoboto:300,400,500,700' rel='stylesheet' type='text/css'>

<!--[if lt IE 9]>
  <script type="text/javascript" src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<title><%= _("Save the Planet - Unite the Armies!") %></title>

<script>
  var recently_added_votes_path = '<%= recently_added_votes_path(format: :json) %>'
</script>

<%= javascript_importmap_tags %>

<%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
<%= stylesheet_link_tag 'flags.css', "data-turbo-track": "reload" %>
<%# stylesheet_link_tag 'bootstrap-3.3.4.css', "data-turbo-track": "reload" %>

<%= javascript_include_tag 'jquery' %>
<%= javascript_include_tag 'jquery_ujs' %>
<%= javascript_include_tag 'countries' %>
<%= javascript_include_tag 'timber.master.min.js' %>
<%= javascript_include_tag 'flash_messages' %>
<%= javascript_include_tag 'jquery.cslider' %>
<%= javascript_include_tag 'jquery.flexisel' %>
<%= javascript_include_tag 'modernizr.custom.28468' %>
<%= javascript_include_tag 'owl.carousel.js' %>
<%= javascript_include_tag 'responsive-nav' %>
<%= javascript_include_tag 'responsiveslides.min' %>
<%= javascript_include_tag 'slideshow.js' %>
<%= javascript_include_tag 'application', type: 'module' %>

<!-- Load Facebook SDK for JavaScript -->
<div id="fb-root"></div>
<script>(function(d, s, id) {
var js, fjs = d.getElementsByTagName(s)[0];
if (d.getElementById(id)) return;
js = d.createElement(s); js.id = id;
js.src = "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0";
fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<%= csrf_meta_tags %>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-10604388-4', 'auto');
  ga('send', 'pageview');
</script>

<%
  recaplocale = (locale == "zh") ? "zh-CH" : locale
%>
<script src='https://www.google.com/recaptcha/api.js?hl=<%= recaplocale %>'></script>

app/views/application/_header.html.erb
<!-- Header -->
<header class="header header-fixed header-fixed-on-mobile header-transparent" data-sticky-threshold="window-height" data-bkg-threshold="100">
  <div class="header-inner">
    <div class="row nav-bar">
      <div class="share-buttons">
        <!-- Your share button code -->
        <div class="fb-share-button"
          data-href="<%= UNITE_ROOT_URL%>"
          data-layout="button">
        </div>
        <div>
          <a class="twitter share-button" href="http://twitter.com/intent/tweet?text=Sign%20an%20appeal%20for%20the%20UN%20to%20ask%20armies%20to%20participate%20on%20the%20preventive%20work%20against%20climate%20catastrophe.%20http%3A%2F%2Funite-the-armies.org%2F">
           Tweet
          </a>
        </div>
      </div>
      <div class="column width-12 nav-bar-inner">
        <div class="logo" id="logo123">
          <div class="logo-inner">
            <%= link_to image_tag(UNITE_LOGO_DARK, alt: "Logo"), locale_root_path(locale: locale), :class => "no-transition" %>
            <%= link_to image_tag(UNITE_LOGO, alt: "Logo"), locale_root_path(locale: locale), :class => "no-transition" %>
          </div>
        </div>
        <nav class="navigation nav-block secondary-navigation nav-right">
          <ul>
            <li class="aux-navigation hide">
              <!-- Aux Navigation -->
              <a href="#" class="navigation-show overlay-nav-show nav-icon">
                <span class="icon-menu"></span>
              </a>
            </li>
          </ul>
        </nav>
        <nav class="navigation nav-block primary-navigation nav-right no-margin-right">
          <ul>
            <li>
              <%= link_to _("Supporters"), votes_path(locale: locale), :class => "contains-sub-menu", data: { :no_turbolink => true } %>
            </li>
            <li>
              <%= link_to _("Read more"), appeal_path(locale: locale), :class => "contains-sub-menu", data: { :no_turbolink => true } %>
            </li>
            <li>
              <%= link_to _("Support now"), new_vote_path(locale: locale), :class => "contains-sub-menu", data: { :no_turbolink => true } %>
            </li>
            <%= render partial: "flags" %>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</header>
<!-- Header End -->

app/views/application/_overlay_navigation.html.erb
<!-- Overlay Navigation Menu -->
<div class="overlay-navigation-wrapper enter-bottom" data-no-scrollbar data-animation="slide-in">
  <div class="overlay-navigation-scroll-pane">
    <div class="overlay-navigation-inner">
      <div class="v-align-middle">
	<div class="overlay-navigation-header row collapse full-width">
	  <div class="column width-12">
	    <div class="navigation-hide overlay-nav-hide">
	      <a href="#">
		<span class="icon-cancel"></span>
	      </a>
	    </div>
	  </div>
	</div>
	<div class="row collapse full-width">
	  <div class="column width-12">
	    <nav class="overlay-navigation nav-block">
	      <h4 class="menu-title"><%= _("Menu") %></h4>
	      <ul>
                <%= render partial: "flags" %>
	      </ul>
	    </nav>
	  </div>
	</div>
	<div class="overlay-navigation-footer row full-width">
	  <div class="column width-12 no-padding">
	    <p class="copyright no-margin-bottom">
              &copy; 2016 UNITE THE ARMIES. All Rights Reserved.</p>
	  </div>
	</div>
      </div>
    </div>
  </div>
</div>
<!-- Overlay Navigation Menu End -->

app/views/application/_top_nav.html.erb
    <li>
      <a class="contains-sub-menu current" data-no-turbolink='true' href=<%= url_for only_path: false, locale: :ar %>>
        <%= image_tag "blank.gif", class: "flag flag-sa" %>
      </a>
    </li>
    <li>
      <a class="contains-sub-menu current" data-no-turbolink='true' href=<%= url_for only_path: false, locale: :zh %>>
        <%= image_tag "blank.gif", class: "flag flag-cn" %>
      </a>
    </li>
    <li>
      <a class="contains-sub-menu current" data-no-turbolink='true' href=<%= url_for only_path: false, locale: :en %>>
        <%= image_tag "blank.gif", class: "flag flag-gb" %>
      </a>
    </li>
    <li>
      <a class="contains-sub-menu current" data-no-turbolink='true' href=<%= url_for only_path: false, locale: :fr %>>
        <%= image_tag "blank.gif", class: "flag flag-fr" %>
      </a>
    </li>
    <li>
      <a class="contains-sub-menu current" data-no-turbolink='true' href=<%= url_for only_path: false, locale: :ru %>>
        <%= image_tag "blank.gif", class: "flag flag-ru" %>                
      </a>
    </li>
    <li>
      <a class="contains-sub-menu current" data-no-turbolink='true' href=<%= url_for only_path: false, locale: :es %>>
        <%= image_tag "blank.gif", class: "flag flag-es" %>
      </a>
    </li>
    <li>
      <a class="contains-sub-menu current" data-no-turbolink='true' href=<%= url_for only_path: false, locale: :fi %>>
        <%= image_tag "blank.gif", class: "flag flag-fi" %>
      </a>
    </li>