config/routes.rb
Rails.application.routes.draw do   
  get 'hello_world', to: 'hello_world#index'
  root 'welcome#index'

  get 'votes/recently_added' => 'votes#recently_added', as: :recently_added_votes
  get 'votes/add_parent' => 'votes#add_parent', as: :add_parent_vote
  post 'votes/email_invite' => 'votes#email_invite', as: :email_invite_votes

  get 'admin/:admin_hash' => 'welcome#admin', as: :admin_index
  post 'admin/:admin_hash' => 'welcome#admin_upload', as: :admin_upload

  scope "(:locale)" do
    get '' => 'welcome#index', as: :locale_root
    get 'appeal' => 'welcome#appeal', as: :appeal
    resources :votes, :only => [:new, :index, :create]
    resources :comments, :only => [:new, :index, :create]
    get 'votes/:secret_token' => 'votes#show', as: :vote
    get 'download' => 'welcome#download', as: :download
  end

end

app/models/vote.rb
require "ostruct"

class Vote < ApplicationRecord
  # include Humanizer
  # require_human_on :create, :unless => :bypass_humanizer
  attr_accessor :bypass_humanizer
  attr_reader :ago

  validates :name, presence: true
  validates :country, presence: true
  validates :email, confirmation: true
  validates :email, presence: true, uniqueness: true, email: true
  validates :email_confirmation, presence: true
  validates :ip, presence: true
  validates_format_of :ip, :with => /\A(\d{1,3}\.){3}\d{1,3}\z/
  validate :validate_country_code

  after_initialize :strip_email
  after_initialize :downcase_country_code
  before_save :add_secret_token
  before_save :add_vote_count

  has_many :votes, foreign_key: :vote_id
  has_many :comments, foreign_key: :vote_id
  #belongs_to :vote, counter_cache: true


  def ago
    showHours = I18n.locale == :en || I18n.locale == :fi
    diff = TimeDifference.between(Time.zone.now, created_at).in_each_component
    diff = OpenStruct.new(diff)
    if diff.seconds < 60
      ago = "%.0f" % diff.seconds.floor
      ago_string = diff.seconds < 2 ? _("second") : _("seconds")
    elsif diff.minutes < 60
      ago = "%.0f" % diff.minutes.floor
      ago_string = diff.minutes < 2 ? _("minute") : _("minutes")
    elsif diff.hours < 24 && showHours
      ago = "%.0f" % diff.hours.floor
      ago_string = diff.hours < 2 ? _("hour") : _("hours")
    else
      ago = showHours ? ("%.0f" % diff.days.floor) : ("%.2f" % diff.days)
      ago_string = diff.days < 2 ? _("day") : _("days")
    end
    "#{ago} #{ago_string}"
  end

  # Strip email of whitespace
  def strip_email
    self.email = email.strip if self.has_attribute?(:email) && email
    self.email_confirmation.strip! if email_confirmation
  end

  # Country code is always saved with downcased letters
  def downcase_country_code
    self.country.downcase! unless country.blank?
  end

  def validate_country_code
    if country.blank? || Country.codes.index(country.upcase).nil?
      errors.add(:country, "is not valid")
    end
  end

  def votes_missed
    VoteCount.target_vote_count - VoteCount.total
  end

  # Vote#order_number as the total number of all votes
  def add_vote_count
    Rails.logger.debug("Adding vote count for #{self.inspect}")
    vote_count = VoteCount.add_vote(self)
    self.order_number = VoteCount.total
  end

  # We do not allow duplicate tokens, lets be sure there is no equal
  # token already in database.
  def add_secret_token
    while token = SecureRandom.hex(64) do
      if Vote.where(secret_token: token).blank?
        require 'digest/md5'
        digest = Digest::MD5.hexdigest(token)
        self.secret_token = token
        self.md5_secret_token = digest
        break
      end
    end
  end

  def email_invite options
    return unless options[:name]
    return unless options[:email]
    return unless options[:language]
    options = options.merge(inviter_name: name, token: md5_secret_token)
    VoteMailer.email_invite(options).deliver_now
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  helper_method :country_code
  helper_method :country_votes

  def new
    clear

    @vote = Vote.new
    respond_to do |format|
      format.html do
        if request.xhr?
          render layout: false
        end
      end
    end
  end

  # Share only with ajax
  def email_invite
    @vote = Vote.where(md5_secret_token: params[:t]).first
    unless @vote
      flash[:error] = _("There was an error")
      head :bad_request
      return
    end

    unless RecaptchaVerifier.verify(params["g-recaptcha-response"])
      flash[:error] = _("There was an error with human verifying")
      head :bad_request
      return
    end

    # Share a vote with ActionMailer. If everything is ok, return 200.
    @share_valid = @vote.email_invite(params)

    respond_to do |format|
      format.html do
        if @share_valid
          flash[:success] = _("Invitation has been sent, thank you!")
          head :ok
        else
          flash[:error] = _("There was an error")
          head :bad_request
        end
      end
    end
  end

  # Add parent vote id to session and redirect to new vote.
  #
  # Use md5 crypted secret token in parameters, this way token cannot be
  # used as a part of the url.
  def add_parent
    vote = Vote.where(md5_secret_token: params[:t]).first
    if vote
      session[:parent_vote_id] = vote.id
    end
    redirect_to action: :new, locale: locale
  end

  # If session votes[:parent_id] exists, add parent to this vote
  def create
    @vote = Vote.new(vote_params)
    @vote.ip = request.env["REMOTE_ADDR"]
    @vote.bypass_humanizer = true if Rails.env.test?

    unless RecaptchaVerifier.verify(params["g-recaptcha-response"])
      redirect_to new_vote_path(locale: locale)
      return
    end

    # If session contains parent vote id, add this vote to parent vote
    # votes association.
    if session[:parent_vote_id]
      parent_vote = Vote.where(id: session[:parent_vote_id])[0]
      parent_vote.votes << @vote if parent_vote
    end

    @vote.save if @vote.new_record?

    # Remove session key after succesfull save
    if @vote.valid?
      session.delete :parent_vote_id

      # If sent_count amount of votes is added after last backup email,
      # send a backup email.
      uas = UaSetting.instance
      total = uas.vote_count.to_i + Rails.configuration.x.send_count
      if VoteCount.total >= total
        uas.send!
      end
    end

    respond_to do |format|
      format.html do
        if request.xhr?
          if @vote.valid?
            VoteMailer.sign_up(@vote).deliver_later
            flash[:success] = _("Thank you for your vote!")
            head :ok
          else
            flash[:error] = _("There was an error while adding your vote")
            head :bad_request
          end
        else
          if @vote.valid?
            VoteMailer.sign_up(@vote).deliver_later
            flash[:success] = _("Thank you for your vote!")
            redirect_to vote_path(locale: locale, secret_token: @vote.secret_token)
          else
            #flash[:error] = "There was an error while adding your vote"
            #redirect_to new_vote_path(locale: locale, anchor: "sign")
            render :new
          end
        end
      end
    end
  end

  def index
    @votes = VoteCount.all
    @sorted_votes = @votes.sort { |a,b| b.count <=> a.count }
  end

  # Do not return votes which has created_at in future
  def recently_added
    @votes = Vote.select(:id, :country,:name, :created_at).where("created_at <= ?", Time.now).last(6)
    votes = @votes.map do |vote|
      vote_h = vote.attributes.to_h
      vote_h[:ago] = vote.ago
      vote_h
    end
    render :json => votes.to_json
  end

  def clear
    session.delete :current_vote_id
  end

  def show
    @vote = Vote.where(secret_token: params[:secret_token]).first
    if @vote.blank?
      redirect_to votes_path(locale: locale)
      return
    end

    # Store current vote to session to allow commenting in contex of
    # this vote.
    session[:current_vote_id] = @vote.id

    @votes_count = @vote.votes_count ||= 0
  end

  private


  # TODO: return default country instead of nil.
  def country_code
    return nil unless request.params
    vote = request.params[:vote] if request.params.has_key?(:vote)
    return nil if vote.blank?
    country_code = vote[:country] if vote.has_key?(:country)
    return nil if country_code.blank?
    #return request[:vote][:country] if request[:vote] and request[:vote][:country]
    country_code
  end

  def language_code
    return "en" unless language_code_full
    language_code_full.split("-")[0]
  end

  def language_code_full
    http_accept_language.user_preferred_languages.first
  end

  def vote_params
    params.require(:vote).permit(:name, :email, :email_confirmation, :country, :humanizer_answer, :humanizer_question_id)
  end

end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/votes/_new_form.html.erb
<div class="new_vote_form">
<% 
   remote = request.xhr? ? true : false   
%>

<%= form_for @vote, url: {action: "create"}, html: {class: "nifty_form"}, remote: remote do |f| %>
<% if @vote.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@vote.errors.count, "error") %> 
      prohibited this vote from being saved:
    </h2>
    <ul>
      <% @vote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>  

<div id="sign" class="ua-sign-the-petition">
  <h1><%= _("Support the Initiative") %></h1>
  <br/>
  <p class="lead"><%= _("We suggest the United Nations presents a global initiative for a redeployment of the world’s armed forces into the new significant environmental tasks as soon as possible.") %></p>

  <div class="field">
    <%= _("Name") %> (*) </br>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="field">
    <%= _("Email") %> (*) </br>
    <%= f.text_field :email, :class => "form-control" %>
  </div>
  <div class="field">
    <%= _("Email Confirmation") %> (*) </br>
    <%= f.text_field :email_confirmation, :class => "form-control" %>
  </div>
  <div class="field">
    <%= _("Country") %> (*)
  </div>
  <div class="field">
    <%= f.select :country, options_for_select([["", "", {:selected => true, :disabled => true, :hidden => true}]] + Country.for_select, country_code), {}, :class => "form-control" %>
  </div></br>
  
  <div class="field">
    <div class="g-recaptcha" data-sitekey="6LfwgBQTAAAAAJrdJfpdvnMhibW4iUFJRdlK0ZXb"></div>
  </div>

  <div class="field"><%= _("You can also contribute to the discussion after signing. You will get a separate message of that by email.") %></div>

  <div class="actions">
    <%= f.submit _("Send"), :class => "btn btn-primary form-control" %>
  </div>

  <% if locale == :fi %>
    <div>
      <%= link_to votes_path(locale: locale), { :class => "button large bkg-black thick bkg-hover-white color-white color-hover-black text-uppercase mb-90", :data => { :no_turbolink => true }} do %>
          <span class="icon-add-user left"></span>

          <p>Katso ketkä ovat kannattaneet!</p>
      <% end %>
    </div>
  <% end %>
</div>

<% end %>

</div>

app/views/votes/_share_vote.html.erb
<%= form_tag email_invite_votes_path, remote: true do %>
<% if @vote.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@vote.errors.count, "error") %> 
      prohibited this vote from being saved:
    </h2>
    <ul>
      <% @vote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>  

<div>
  <%= hidden_field_tag(:t, @vote.md5_secret_token) %>
  <div class="field">
    <%= label_tag _("Choose the language of the invitation letter") %>
    <%= select_tag :language, options_for_select(Language.translated_select_options), :class => "form-control" %>
  </div>
  <div class="field">
    <%= label_tag _("Name of your friend") + " *" %>
    <%= text_field_tag :name, nil, :class => "form-control", :style => "color: black !important" %>
  </div>
  <div class="field">
    <%= label_tag _("Your friends email address") + " *" %>
    <%= text_field_tag :email, nil, :class => "form-control", :style => "color: black !important" %>
  </div>
  <div class="field">
    <%= label_tag _("Email Confirmation") + " *" %>
    <%= text_field_tag :email_confirmation, nil, :class => "form-control", :style => "color: black !important" %>
  </div>
  <div class="field">
    <div class="g-recaptcha" data-sitekey="6LfwgBQTAAAAAJrdJfpdvnMhibW4iUFJRdlK0ZXb"></div>
  </div>
  <div class="field">
    <%= submit_tag _("Send"), :class => "button xlarge bkg-black thick bkg-hover-white color-white color-hover-black text-uppercase mb-90" %>
  </div>
</div>
<% end %>

app/views/votes/index.html.erb
<!-- Content -->

  <!-- Fullscreen Slider Section -->
  <section class="section-block featured-media tm-slider-parallax-container">
    <div class="tm-slider-container full-width-slider" data-featured-slider data-progress-bar="false" data-parallax data-parallax-fade-out data-auto-advance data-animation="slide" data-scale-under="960">
      <ul class="tms-slides">
        <li class="tms-slide" data-image data-force-fit data-overlay-bkg-color="#000000" data-overlay-bkg-opacity="0.3">
          <div class="tms-content">
            <div class="tms-content-inner center left-on-mobile v-align-middle">
              <div class="row">
                <div class="column width-12">
                  <h1 class="tms-caption title-large color-white lspacing-medium no-margin-bottom weight-bold" data-animate-in="opacity:0;scale:1.5px;duration:600ms;easing:easeFastSlow;"
                      data-no-scale>
                    <%= _("%{count} votes") % { count: number_with_delimiter(VoteCount.total) } %>
                  </h1>
                  <div class="clear"></div>
                  <h5 class="tms-caption color-white lspacing-medium mt-20"
                      data-animate-in="opacity:0;transY:50px;duration:600ms;delay:300ms;easing:easeFastSlow;" data-no-scale>
                    <%= _("More work must be done") %>
                  </h5>
                </div>
              </div>
            </div>
          </div>
          <img data-src="/images/frontpage-slides/slide-2.jpg" src="/images/blank.png" alt=""/>
        </li>
      </ul>
    </div>
  </section>
  <!-- Fullscreen Slider Section End -->

   <% if locale == :fi %>
  <!-- Feature Column Section -->
      <section>
        <div id="featured-trips" class="section-block replicable-content">
          <div class="row">
            <div class="column width-8 offset-2">
              <div class="feature-column small center">
                <div class="feature-text">
                  <h5 class="text-uppercase text-small weight-light">Seuraavat, eri aloja edustavat, merkittävät professorit ovat antaneet vetoomukselle kannatuksensa:
                  </h5>

                </div>
              </div>
            </div>

          </div>
          <div class="row">

            <div class="column width-4 offset-2">
              <div class="feature-column small center">
                <div class="feature-text">
                  <p class="mb-mobile-30">
                    Mikael Fortelius, evoluutiopaleontologia<br>
                    Pekka Kauppi, ympäristönsuojelu <br>
                    Anto Leikola, oppihistoria <br>
                    Pentti Murole, kaupunkisuunnittelu <br>
                    Heikki Palva, arabian kieli <br>
                    Juha Pentikäinen, pohjoinen etnografia <br></p>
                </div>
              </div>
            </div>

            <div class="column width-6">
              <div class="feature-column small center">
                <div class="feature-text">
                  <p class="mb-mobile-30">
                    Eero Saksela, lääketiede <br>
                    Jan Söderlund, arkkitehtuuri <br>
                    Peter Tigerstedt, kasvitiede <br>
                    Tuija Vihavainen, puutekniikka <br>
                    Reijo Vihko, lääketiede <br>
                    Yrjö Wiherheimo, teollinen muotoilu </p>
                </div>
              </div>
            </div>
          </div>
        </div>
  <!-- Feature Column Section end -->
  
  <!-- Feature Column Section -->
        <div id="featured-trips" class="section-block replicable-content">
          <div class="row">
            <div class="column width-8 offset-2">
              <div class="feature-column small center">
                <div class="feature-text">
                  <h5 class="text-uppercase text-small weight-light">Seuraavat suomalaiset kirjailijat ja suomentajat ovat antaneet vetoomukselle kannatuksensa:</h5>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="column width-4 offset-2">
              <div class="feature-column small center">
                <div class="feature-text">
                  <p class="mb-mobile-30">
                    Maikki Harjanne, kirjailija<br/>
                    Arto Häilä, suomentaja<br/>
                    Timo Hännikäinen, kirjailija<br/>
                    Risto Isomäki, kirjailija<br/>
                    Tiina Krohn, kirjailija<br/>
                    Pentti Linkola, kirjailija<br/>
                </div>
              </div>
            </div>

            <div class="column width-6">
              <div class="feature-column small center">
                <div class="feature-text">
                  <p class="mb-mobile-30">
                    Harri Manner, kirjailija<br>
                    Hannu Mäkelä, kirjailija<br>
                    Kimmo Pietiläinen, suomentaja<br>
                    Mauno Saari, kirjailija<br>
                    Hannu Salama, kirjailija<br>
                    Kaari Utrio, kirjailija</p>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div id="featured-trips" class="section-block replicable-content">
          <div class="row">
            <div class="column width-8 offset-2">
              <div class="feature-column small center">
                <div class="feature-text">
                  <h5 class="text-uppercase text-small weight-light">Seuraavat merkittävät entiset kansanedustajat
                    ovat allekirjoittaneet vetoomuksen:</h5>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="column width-4 offset-2">
              <div class="feature-column small center">
                <div class="feature-text">
                  <p class="mb-mobile-30">
                    Claes Andersson<br/>
                    Sirpa Asko-Seljavaara<br/>
                    Mikko Elo<br/>
                    Heidi Hautala<br/>
                    Timo Juurikkala<br/>
                    Risto Kuisma<br/>
                  </p>
                </div>
              </div>
            </div>

            <div class="column width-6">
              <div class="feature-column small center">
                <div class="feature-text">
                  <p class="mb-mobile-30">
                    Kalle Könkkölä<br/>
                    Markku Laukkanen<br/>
                    Outi Ojala<br/>
                    Kati Peltola<br/>
                    Pentti Tiusanen<br/>
                    Marjatta Vehkaoja<br/>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>

      </section>

      <section>
        <div id="featured-trips" class="section-block replicable-content center">
          <div class="row">
            <%= link_to new_vote_path(locale: locale), { :class => "button xlarge bkg-black thick bkg-hover-white color-white color-hover-black text-uppercase mb-90", :data => { :no_turbolink => true }} do %>
                <span class="icon-add-user left"></span>
                <%= _("Support now") %>
            <% end %>
          </div>
        </div>
      </section>

<!-- Feature Column Section end -->
<% end %>

  <!-- Show country votes -->
  <section class="section-block feature-1" style="min-height: 200px">
    <div class="row no-padding-bottom">
      <table id="country_votes_table" class="table" style="table-layout: fixed; width: 100%">
        <% @sorted_votes.each do |vote_count| %>
            <tr>
              <td class="country_flag"><%= image_tag "blank.gif", :class => ["flag_small", vote_count.country] %></td>
              <td class="country"><%= Country.code_to_name(vote_count.country) %></td>
              <td class="vote_percentage">
                <div style="width:<%= vote_count.diagram_width %>%; height:30px; background:green"/>
              </td>
              <td class="vote_count"><%= number_with_delimiter(vote_count.count) %></td>
            </tr>
        <% end %>
      </table>
    </div>
  </section>

<!-- Content End -->

app/views/votes/new.html.erb
<!-- Content -->
<div class="content clearfix">

  <!-- Fullscreen Slider Section -->
  <section class="section-block featured-media tm-slider-parallax-container">
    <div class="tm-slider-container full-width-slider" data-featured-slider data-progress-bar="false" data-parallax data-parallax-fade-out data-auto-advance data-animation="slide" data-scale-under="960">
      <ul class="tms-slides">
        <li class="tms-slide" data-image data-force-fit data-overlay-bkg-color="#000000" data-overlay-bkg-opacity="0.0">
          <div class="tms-content">
            <div class="tms-content-inner center left-on-mobile v-align-middle">
              <div class="row">
                <div class="column width-12">
                  <h1 class="tms-caption title-xlarge color-white lspacing-medium no-margin-bottom weight-bold" data-animate-in="opacity:0;scale:1.5px;duration:600ms;easing:easeFastSlow;"
                      data-no-scale>
                    <%= _("Support") %>
                  </h1>
                  <div class="clear"></div>
                  <h5 class="tms-caption color-white lspacing-medium mt-20"
                      data-animate-in="opacity:0;transY:50px;duration:600ms;delay:300ms;easing:easeFastSlow;" data-no-scale>
                    <%= _("Radical actions are urgently needed to save our planet.") %>
                  </h5>
                </div>
              </div>
            </div>
          </div>
          <img data-src="/images/frontpage-slides/slide-1.jpg" src="/images/blank.png" alt=""/>
        </li>
      </ul>
    </div>
  </section>
  <!-- Fullscreen Slider Section End -->

  
</div>
<!-- Content End -->

<!-- Feature Section 1 -->
<section class="section-block feature-1 bkg-white">
  <div class="row no-padding-bottom">
    <div class="column width-6 offset-3">
      <div class="feature-content">
	<div class="feature-content-inner">
	  
          <%= render partial: "new_form" %>
          
	</div>
      </div>
    </div>
  </div>
  
</section>
<!-- Feature Section 1 End -->

app/views/votes/show.html.erb
<!-- Content -->
<div class="content clearfix">
  <!-- Fullscreen Slider Section -->
  <section class="section-block featured-media tm-slider-parallax-container">
    <div class="tm-slider-container full-width-slider" data-featured-slider data-progress-bar="false" data-parallax data-parallax-fade-out data-auto-advance data-animation="slide" data-scale-under="960">
      <ul class="tms-slides">
        <li class="tms-slide" data-image data-force-fit data-overlay-bkg-color="#000000" data-overlay-bkg-opacity="0.0">
          <div class="tms-content">
            <div class="tms-content-inner center left-on-mobile v-align-middle">
              <div class="row">
                <div class="column width-12">
                  <h1 class="tms-caption title-xlarge color-white lspacing-medium no-margin-bottom weight-bold" data-animate-in="opacity:0;scale:1.5px;duration:600ms;easing:easeFastSlow;" data-no-scale>
                    <%= _("Thank you for your support %{name}") % {name: @vote.name} %>
                  </h1>
                  <div class="clear"></div>
                  <h5 class="tms-caption color-white lspacing-medium mt-20" data-animate-in="opacity:0;transY:50px;duration:600ms;delay:300ms;easing:easeFastSlow;" data-no-scale>
                    <%= _("This is your private vote") %>
                  </h5>
                </div>
              </div>
            </div>
          </div>
          <img data-src="/images/frontpage-slides/slide-5.jpg" src="/images/blank.png" alt=""/>
        </li>
      </ul>
    </div>
  </section>
  <!-- Fullscreen Slider Section End -->

  <div id="featured-trips" class="section-block replicable-content">
    <div class="row">
      <div class="column width-4">
	<div class="feature-column small left">
          <p><%= _("Do not share this direct link with anybody. Instead, you can use a form below to share a public version of this vote with your friends.") %> </p>
        </div>
      </div>
      <div class="column width-4">
	<div class="feature-column small left">
          <%= _("Your supporter number is %{count}.") % {count: number_with_delimiter(@vote.order_number)} %>
          <%= _("We still miss %{count} of the %{target}.") % {count: number_with_delimiter(@vote.votes_missed), target: number_with_delimiter(VoteCount.target_vote_count)} %>
        </div>
      </div>
      <div class="column width-4">
	      <div class="feature-column small left">
          <% if locale == :en || locale == :fi %>
              <%= _("Thank you for spreading the word! Click") %>
              <a class="show-on-click" href="#" onclick="event.preventDefault()"><%= _("here") %><span><%= number_with_delimiter(@votes_count) %></span></a><%= _("if you wish see how many people have signed by following your personal invitation.") %>
          <% else %>
              <%= _("You have helped campaign by having %{count} people signed after you.") % {count: number_with_delimiter(@votes_count)} %>
              <%= _("You have added %{count} comments.") % {count: number_with_delimiter(@vote.comments.size)} %>
              <%= _("Signatures! Let’s work further!") %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="section-block grid-container fade-in-progressively bkg-charcoal color-white" data-layout-mode="masonry" data-grid-ratio="1" data-animate-filter-duration="0.7" data-set-dimensions data-animate-resize data-animate-resize-duration="0.8">   
    <div class="row">
      <div class="column width-12">
        <h2><%= _("Add a comment") %></h2>
        <p>
          <%= _("You can now add a comment.") %>
        </p>
        <%= button_tag(_("Comment"), :class => "button xlarge bkg-black thick bkg-hover-white color-white color-hover-black text-uppercase mb-90", :data => { :no_turbolink => true }, onClick: "window.location='#{new_comment_path}'") %>
      </div>
    </div>
  </div>

  <div class="section-block replicable-content bkg-grey-ultralight">
    <div class="row">
      <div class="column width-12">
        <h2><%= _("Share with social media") %></h2>
        <p>
          <%= social_share_button_tag("Save the Planet - Unite the Armies", url: add_parent_vote_url(t: @vote.md5_secret_token)) %>
        </p>
      </div>
    </div>
  </div>

  <div class="section-block grid-container fade-in-progressively bkg-charcoal color-white" data-layout-mode="masonry" data-grid-ratio="1" data-animate-filter-duration="0.7" data-set-dimensions data-animate-resize data-animate-resize-duration="0.8">   
    <div class="row">
      <div class="column width-12">
        <h2><%= _("Share email with your friends") %></h2>
        <p>
          <%= _("Invite your friends. Fill out a form below and information will be sent to given email") %>
        </p> 
        <%= render partial: "share_vote" %>
      </div>
    </div>

  </div>
</div>